zuul:
  #全部服务忽略敏感头(全部服务都可以传递cookie)
  sensitive-headers: 
  routes:
    # 路由自定义路径名, 完整写法
    #    customRouteRule1:
    #      path: /myProduct/**
    #      serviceId: product
    # 路由自定义路径名, 简洁写法
    product: /myProduct/**
  # 排除某些路由
  ignored-patterns:
    - /**/product/listForOrder
spring:
  redis:
    host: 192.168.31.57
    port: 6379