spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 
    url: jdbc:mysql://192.168.31.57:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false