spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 
    url: jdbc:mysql://192.168.31.57:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.31.57
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.31.57
    port: 6379
  zipkin:
    base-url: http://192.168.31.57:9411/
    sender:
      type: web
  sleuth:
    sampler:
      #      发送到zipkin的抽样率
      probability: 1
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
env: dev
logging:
  level:
    org:
      springframework:
        cloud:
          openfeign: debug